import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Box, Container } from "@chakra-ui/react";
import Header from "@/components/organisms/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Box position="fixed" w="100%" top={0} m={0} p={0} zIndex={100}>
        <Header />
      </Box>
      <Container
        maxW="full"
        flexGrow={1}
      >
        {children}
      </Container>

    </>
  );
}
