



import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import Header from "@/components/organisms/Header";
import Footer from "@/components/organisms/Footer";
import { Box, Center, Flex } from "@chakra-ui/react";
import Sidebar from "@/components/organisms/Sidebar";


const prompt = Prompt({
  weight: ["400", "600"],
  subsets: ["latin"],
  display:"swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={prompt.className}>
      <Center>
        <Flex direction="column"  width="1200px" maxW="90%" 
        gap="28px" height="100vh">
          <Header/>
          {children}
          <Footer/>
        </Flex>
      </Center>
    </html>
  );
}
