import { DefaultLayout } from "@/components/templates/DefaultLayout";
import { Box, Center, HStack, Heading, Image, Mark, Text, VStack} from "@chakra-ui/react";

import homePageImg from "@/assets/image/homePage.png"
import Link from "next/link";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {

  function teste() {
    console.log("Teste")
  }

  return (
    <Center mt="50px" pl="60px">
      <HStack justifyContent="space-around" alignItems="center" mt="200px">
        <VStack justifyContent="center" alignItems="center" >
          <Text variant="primary" as='h2' fontSize="80px"  >
            Uma Plataforma para <Mark variant="gradientGold"> Calculos Tributários </Mark>
          </Text>
          <Text lineHeight={1} mt="10px" color="gray" >Projeto desenvolvido pensando em você Cliente e Contador</Text>
          <Box mt={5}>
            <Link href="/Ferramentas">
              <Text fontSize="40px" fontWeight="bold" _hover={{color:"#84D571"}} bgGradient="linear(to-r, #84D571, #296B18)" bgClip="text">Faça já a sua Simulação</Text>
            </Link>
          </Box>
        </VStack>
      </HStack>
    </Center>
  );
}

Home.getLayout = function getLayout(page: React.ReactElement) {
  return (
    <DefaultLayout>{page}</DefaultLayout>
  );
};